project_name: kubectl-schema
release:
  github:
    owner: mattfenwick
    name: kubectl-schema
  prerelease: auto
builds:
  - id: kubectl-schema
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/schema/main.go
    ldflags: -s -w
      -X github.com/mattfenwick/schema/pkg/swagger.version={{.Version}}
      -X github.com/mattfenwick/schema/pkg/swagger.gitSHA={{.Commit}}
      -X github.com/mattfenwick/schema/pkg/swagger.buildTime={{.Date}}
archives:
  - id: kubectl-schema
    builds:
    - kubectl-schema
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
