name: Go

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./cmd/schema/main.go

      - name: Format
        run: go fmt ./cmd/... ./pkg/...

      - name: Vet
        run: go vet -v ./cmd/... ./pkg/...

      - name: Test
        run: go test -v ./pkg/...
